version: "3"

services:
  leafchat-database:
    container_name: leafchat-database
    image: postgres:13-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    command: postgres -p 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: leafchat
    volumes:
      - /usr/local/leafchat-pg/data:/var/lib/postgresql/data
    networks:
      - leafchat-network

  leafchat-mongodb:
    container_name: leafchat-mongodb
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /usr/local/leafchat-mongodb/data:/var/lib/mongodb/data
    networks:
      - leafchat-network

networks:
  leafchat-network:
    driver: bridge
